import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import ReactQueryProvider from "@/app/ReactQueryProvider";
import {ReactQueryDevtools} from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
    title: "Country",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <ReactQueryProvider>
            {children}
            <ReactQueryDevtools initialIsOpen={false}/>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
